# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='имя')),
                ('places', models.CharField(db_index=True, max_length=250, verbose_name='города')),
                ('phones', models.CharField(db_index=True, max_length=250, verbose_name='телефоны')),
                ('email', models.EmailField(db_index=True, max_length=250, verbose_name='email')),
                ('requisites', models.TextField(verbose_name='реквизиты')),
                ('comments', models.TextField(verbose_name='комментарии')),
            ],
            options={
                'verbose_name_plural': 'Прокатчики',
                'ordering': ['name'],
                'verbose_name': 'Прокатчик',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('todate', models.DateField(db_index=True)),
                ('comments', models.TextField(verbose_name='комментарии')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contlog.Contact', verbose_name='Прокатчик')),
            ],
            options={
                'verbose_name_plural': 'События',
                'ordering': ['-added'],
                'verbose_name': 'Событие',
            },
        ),
        migrations.CreateModel(
            name='Spectacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='цена')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name_plural': 'Спектакли',
                'ordering': ['name'],
                'verbose_name': 'Спектакль',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='spectacle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contlog.Spectacle', verbose_name='Спектакль'),
        ),
    ]
