# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(blank=True, verbose_name='комментарии'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=250, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phones',
            field=models.CharField(blank=True, db_index=True, max_length=250, verbose_name='телефоны'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='places',
            field=models.CharField(blank=True, db_index=True, max_length=250, verbose_name='города'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='requisites',
            field=models.TextField(blank=True, verbose_name='реквизиты'),
        ),
        migrations.AlterField(
            model_name='events',
            name='comments',
            field=models.TextField(blank=True, verbose_name='комментарии'),
        ),
        migrations.AlterField(
            model_name='events',
            name='todate',
            field=models.DateField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='spectacle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='цена'),
        ),
    ]
