# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contlog', '0003_auto_20170402_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lastevent',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=250, verbose_name='последнее событие'),
        ),
    ]
